name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            python -m pip install numpy fitparse fitdecode fit_tool
          fi
          python -m pip install py2app

      - name: Build native sync extension
        run: |
          clang++ -fPIC -bundle -undefined dynamic_lookup \
              -std=c++11 \
              -o libsync.so BOOGER/sync.cpp

      - name: Build .app with py2app
        run: |
          python setup.py py2app

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: PolarGarminSyncSplit-macos
          path: dist/PolarGarminSyncSplit.app
